### ISSUE TITLE
Release 20 - 22 autoupdater fails

### ISSUE THREAD

**Issue by ohyeah2389** [jeffboulanger/DCS-Alternative-Launcher#52]
When launching the latest release (v20), it asks to autoupdate to v22.0.0.0. If you hit yes, it restarts and then on boot it throws this: 

Release 20 (01/01/2000)

DCS.Alternative.Launcher.ServiceModel.IoCResolutionException: Unable to resolve type: DCS.Alternative.Launcher.Services.Settings.SettingsService
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'ReactiveProperty.Core, Version=7.4.1.0, Culture=neutral, PublicKeyToken=910d1732782c71cb'. The system cannot find the file specified.
File name: 'ReactiveProperty.Core, Version=7.4.1.0, Culture=neutral, PublicKeyToken=910d1732782c71cb'
   at DCS.Alternative.Launcher.Services.Settings.SettingsService..ctor()

   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DCS.Alternative.Launcher.ServiceModel.Container.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\ServiceModel\Container.cs:line 2126
   --- End of inner exception stack trace ---
   at DCS.Alternative.Launcher.ServiceModel.Container.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\ServiceModel\Container.cs:line 2130
   at DCS.Alternative.Launcher.ServiceModel.Container.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\ServiceModel\Container.cs:line 2052
   at DCS.Alternative.Launcher.ServiceModel.Container.SingletonFactory.GetObject(Type requestedType, Container container, NamedParameterOverloads parameters, ResolveOptions options) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\ServiceModel\Container.cs:line 2921
   at DCS.Alternative.Launcher.ServiceModel.Container.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\ServiceModel\Container.cs:line 1779
   at DCS.Alternative.Launcher.ServiceModel.Container.Resolve(Type resolveType) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\ServiceModel\Container.cs:line 501
   at DCS.Alternative.Launcher.ServiceModel.Container.Resolve[ResolveType]() in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\ServiceModel\Container.cs:line 628
   at DCS.Alternative.Launcher.Services.Dcs.DcsWorldService..ctor(IContainer container) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\Services\Dcs\DcsWorldService.cs:line 36
   at DCS.Alternative.Launcher.App.RegisterServicesAsync() in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\App.xaml.cs:line 430
   at DCS.Alternative.Launcher.App.App_Startup(Object sender, StartupEventArgs e) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\App.xaml.cs:line 196
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by chazmat** [comment]
Same here.

Release 20 (01.01.2000)

DCS.Alternative.Launcher.ServiceModel.IoCResolutionException: Unable to resolve type: DCS.Alternative.Launcher.Services.Settings.SettingsService
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'ReactiveProperty.Core, Version=7.4.1.0, Culture=neutral, PublicKeyToken=910d1732782c71cb'. The system cannot find the file specified.
File name: 'ReactiveProperty.Core, Version=7.4.1.0, Culture=neutral, PublicKeyToken=910d1732782c71cb'
   at DCS.Alternative.Launcher.Services.Settings.SettingsService..ctor()


   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at DCS.Alternative.Launcher.ServiceModel.Container.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\ServiceModel\Container.cs:line 2126
   --- End of inner exception stack trace ---
   at DCS.Alternative.Launcher.ServiceModel.Container.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\ServiceModel\Container.cs:line 2130
   at DCS.Alternative.Launcher.ServiceModel.Container.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\ServiceModel\Container.cs:line 2052
   at DCS.Alternative.Launcher.ServiceModel.Container.SingletonFactory.GetObject(Type requestedType, Container container, NamedParameterOverloads parameters, ResolveOptions options) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\ServiceModel\Container.cs:line 2921
   at DCS.Alternative.Launcher.ServiceModel.Container.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\ServiceModel\Container.cs:line 1779
   at DCS.Alternative.Launcher.ServiceModel.Container.Resolve(Type resolveType) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\ServiceModel\Container.cs:line 501
   at DCS.Alternative.Launcher.ServiceModel.Container.Resolve[ResolveType]() in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\ServiceModel\Container.cs:line 628
   at DCS.Alternative.Launcher.Services.Dcs.DcsWorldService..ctor(IContainer container) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\Services\Dcs\DcsWorldService.cs:line 36
   at DCS.Alternative.Launcher.App.RegisterServicesAsync() in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\App.xaml.cs:line 430
   at DCS.Alternative.Launcher.App.App_Startup(Object sender, StartupEventArgs e) in C:\Users\fdspr\source\repos\DCS-Alternative-Launcher\DCS.Alternative.Launcher\App.xaml.cs:line 196
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
